---
title: "Lab 1"
author: "C. E. Mori"
date: "2023-01-13"
output: html_document
---

```{r setup, include = TRUE, echo = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) #This will apply to all chunks below.
library(tidyverse)
library(here)
library(sf)
library(tmap)
```

Read in data:

```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))

top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n = 5) %>% #Only retains the top 5 legal status categories, according to number of trees in each category.
  arrange(-tree_count) #Lists the legal status categories in descending order according to tree count.

ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count), #Reorders according to tree count (ascending).
                                y = tree_count)) +
  geom_col() +
  labs(y = "Tree Count", x = "Legal Status") + 
  coord_flip() + #Flips the x and y axes.
  theme_minimal()
```

